### ISSUE TITLE
demo app is bust

### ISSUE THREAD

**Issue by ukd1** [schneems/heroku-bouncer-demo#1]
http://heroku-bouncer-demo.herokuapp.com/ :-1: :(

**Comment by ukd1** [comment]
@schneems I can has fix?

**Comment by schneems** [comment]
We took it down due to security vulnerabilities. I.e. we can't upgrade the app every time a security vulnerability in Rails/Rack/Whatever comes out, also we don't want to expose your heroku credentials to an attacker.

**Comment by ukd1** [comment]
Understood - @schneems perhaps update the docs then?
